CREATE TABLE `ACTOR` (
  `ID` int(11) NOT NULL,
  `OSCARNOMINATIONS` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_ACTOR_ID` FOREIGN KEY (`ID`) REFERENCES `PERSON` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
SELECT * FROM cs5200.ACTOR;