CREATE TABLE `DIRECTOR` (
  `ID` int(11) NOT NULL,
  `OSCARWINS` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_DIRECTOR_ID` FOREIGN KEY (`ID`) REFERENCES `PERSON` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
